spring.datasource.url=jdbc:sqlserver://10.0.11.175:15000;databaseName=WEBDEMO;encrypt=false;trustServerCertificate=true;
spring.datasource.username=esha
spring.datasource.password=ws5000997!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# 로깅 설정
logging.level.com.example.library=DEBUG
logging.level.org.springframework.web=DEBUG

# 서버 포트 설정
server.port=8080

